import CameraSvg from '../assets/svg/camera.svg'
import Scanning from '../assets/svg/scanning.svg'
import Color from '../assets/svg/color.svg'
import Moon from '../assets/svg/moon.svg'
import DownloadSvg from '../assets/svg/download.svg'
import History from '../assets/svg/history.svg'
import Mark from '../assets/svg/mark.svg'
import Play from '../assets/svg/play.svg'
import FirstPage from '../assets/svg/first_page.svg'
import FirstFullPage from '../assets/svg/first_full_page.svg'
import Self from '../assets/svg/slef.svg'
import SelfFull from '../assets/svg/self_full.svg'
import NewInfo from '../assets/svg/new_info.svg'
import NewInfoFull from '../assets/svg/new_info_full.svg'
import Channel from '../assets/svg/channel.svg'
import ChannelFull from '../assets/svg/channel_full.svg'
import Buy from '../assets/svg/buy.svg'
import BuyFull from '../assets/svg/buy_full.svg'
import MsgCircle from '../assets/svg/message.svg'
import MsgCircleFull from '../assets/svg/message_full.svg'
import Person from '../assets/svg/person.svg'
import PersonFull from '../assets/svg/person_full.svg'

export { CameraSvg }
export { Scanning }
export { Color }
export { Moon }
export { DownloadSvg }
export { History }
export { Mark }
export { Play }
export { FirstPage }
export { Self }
export { SelfFull }
export { NewInfo }
export { NewInfoFull }
export { Channel }
export { ChannelFull }
export { Buy }
export { BuyFull }
export { FirstFullPage }
export { MsgCircle }
export { MsgCircleFull }
export { Person }
export { PersonFull }